### ISSUE TITLE
viewing copied speech history displays incorrectly

### ISSUE THREAD

**Issue by ns-studios** [TheQuinbox/cliptools#2]
If I let NVDA say something, and then I press "Copy the currently selected speech history item to clipboard" from speech history addon, and I go to cliptools' "view and edit the current clipboard content", what appears in the box is something like "裐η" (0x8c08 0x140 0x3) for "test" (without quotes).
If I paste the copied history item first, and then re-copy it, it works fine, so maybe something to do with the way cliptools reads or speech history copies things?
NVDA       2021.3.3
Speech history review and copying 2021.1
Clipboard tools for NVDA 2021.1 @TheQuinbox

**Comment by trypsynth** [comment]
Woah, that's weird. I quite honestly have no idea what it's doing, but will definitely investigate. Thanks for opening this.

**Comment by trypsynth** [comment]
This has now been fixed, hopefully.
